### ISSUE TITLE
Thin scroll bar for the script window doesn't work as expected

### ISSUE THREAD

**Issue by HMBM47** [atampy25/quickentity-editor-next#17]
In the rightmost window, the thin scrollbar doesn't work as expected. 
The thin bar can only be selected if it's all the way at the top, and the mouse drags onto it from the very top. 
Any other click on the the thin bar, weather it's the bar itself or an empty spot, the bar just jumps. It can't be clicked and dragged by the mouse. 
The only way to navigate the script with the proper "click and drag", is by using the larger thumbnail bar. 

From what I can see, it looks like putting the mouse any lower than the very top of the thin bar, is actually selecting the bigger thumbnail bar.

Mouse hovering over the very top of the small scroll bar:
![ScrollWheel_VeryTop](https://github.com/atampy25/quickentity-editor-next/assets/20890580/398be509-433c-42e7-b7d6-19bc0804f55f)

Slightly lower:
![ScrollWheel_SlightlyLower](https://github.com/atampy25/quickentity-editor-next/assets/20890580/85ba5712-2cfe-4443-b70d-78ca0c58830e)

**Comment by atampy25** [comment]
Resolved by 97dcc07.

**Comment by HMBM47** [comment]
Unfortunately it has not been fixed on my end.
