### ISSUE TITLE
Properties can be lost when copy/pasting between entities

### ISSUE THREAD

**Issue by JojjeE** [atampy25/quickentity-editor-next#24]
From source, before copying:

![Before](https://github.com/atampy25/quickentity-editor-next/assets/112397648/236f0a0e-56ad-4e67-9209-c8111f0d74fd)

In json this entity is:

```json
{"ee6303c5f489ddf5":{"parent":"3a610fa0b7a52124","name":"FullBody","factory":"0012C9E3ED80E8C9","blueprint":"0026079BF5D4C4EB","properties":{"Spine_Low_RadiusZ":{"type":"float32","value":0.18000000715255737},"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":0},"position":{"x":-0.000005165853963262634,"y":1.2552820294331468e-7,"z":0}}},"Hand_L_Enabled":{"type":"bool","value":false},"Hand_R_Enabled":{"type":"bool","value":false},"Elbow_R_Enabled":{"type":"bool","value":false},"Elbow_L_Enabled":{"type":"bool","value":false},"m_linkedEntity":{"type":"SEntityTemplateReference","value":"3a610fa0b7a52124","postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"3a610fa0b7a52124","postInit":true}}},"origin":"00A415DC958A4B39"}
```

At destination, after pasting:

![After](https://github.com/atampy25/quickentity-editor-next/assets/112397648/dbb1274a-a21e-49e4-ac9c-38166f1bfbe7)

Properties referring to entities that do not exist are culled when entity is pasted. Better to void the value and let user fill them in themselves?

**Comment by atampy25** [comment]
This is intended behaviour but perhaps not good behaviour (TArray property values do the same except they end up with a blank array if there was only one item). I'll change it to setting the value to an empty array.
