### ISSUE TITLE
Error when trying to view / edit tree view node after loading a new game file

### ISSUE THREAD

**Issue by OrfeasZ** [atampy25/quickentity-editor-next#3]
Steps to reproduce:

1. Load a template by using `Load` -> `Load entity from game`.
2. Switch to Tree view and wait for it to load (if it hasn't already).
3. Load a different template in the same way as 1.
4. Wait for it to load.
5. Try to click on any tree view node.

The following error shows up:
![](https://i.nofate.me/zAyV5o9cI1GQxSS.png)

Going to another tab and back fixes this.

**Comment by atampy25** [comment]
I'll look into this.

**Comment by atampy25** [comment]
Resolved in de0908f.
