### ISSUE TITLE
[Request] Accept path strings in template and blueprint fields

### ISSUE THREAD

**Issue by OrfeasZ** [atampy25/quickentity-editor-next#6]
Would be great if resource path strings (eg. `[assembly:/whatever.entity].pc_entitytype`) would be accepted for the `tempHash` and `tbluHash` fields (or some alternative to them), and QNE would automatically hash them, in the same way it does for references and loading game files.

**Comment by atampy25** [comment]
This is probably more a QN thing; I might include this in a future 3.1 release (along with renaming template to factory once and for all).
