### ISSUE TITLE
Cannot scroll through dependencies

### ISSUE THREAD

**Issue by OrfeasZ** [atampy25/quickentity-editor-next#7]
When the file being edited (eg. `007DA19BBE61C3A7`) has too many dependencies, it's not possible to scroll through them:

![](https://i.nofate.me/Kcaxc5VJXZ6ZhSO.png)

**Comment by atampy25** [comment]
This is probably a regression caused by 43dfb21. Will look into it.

**Comment by atampy25** [comment]
I'm able to scroll fine through that brick. Is there any unusual window setup/resolution or similar?

![Image](https://user-images.githubusercontent.com/24306974/196350695-8c314c6c-2f5c-42bb-adb5-981445edd80d.png)

**Comment by OrfeasZ** [comment]
No, regardless of resolution I'm not getting a scrollbar at all. Is there a way to turn on dev tools or something similar?

**Comment by atampy25** [comment]
Dev tools are disabled in release builds. Does the latest portable release from this repository have the same issue?

**Comment by OrfeasZ** [comment]
Portable version has the same issue.

**Comment by atampy25** [comment]
Here's a debug build: [QuickEntity Editor.zip](https://github.com/atampy25/quickentity-editor-next/files/9857609/QuickEntity.Editor.zip)

It should have the inspector and the other dev tools enabled.

**Comment by atampy25** [comment]
This was resolved in 08908dc.
